# Generated by Django 5.1.7 on 2025-03-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('cuisine_general', models.TextField(blank=True, null=True)),
                ('cuisine_specific', models.TextField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('vibe', models.TextField(blank=True, null=True)),
                ('occasions', models.TextField(blank=True, null=True)),
                ('type_of_meal', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('reservation_link', models.URLField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
