# Generated by Django 5.1.7 on 2025-03-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='directions_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
